# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f90676139aa5d7e455c8f86a70353f7724fa7ef53698501a6190535d8bcee933f9a21b7be51df37138717ac172d79683f4f0d6d0d789bed2b67943fc4af72cdc

test:
  secret_key_base: 368669a6580d0b2502cb0b77412a0ff869c9269b995f05743a6aa3563b3197eb95d10b909b8b8a50c8ff2e8f32418efe0fdbde8d719a7529c62fb00922f3f76b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
